### ISSUE TITLE
csvfind -trimspaces issue

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/datatools#2]
-trimspaces doesn't seem to work

Example file: 
[text.txt](https://github.com/caltechlibrary/datatools/files/1556513/text.txt)

Works as expected:
csvfind -i text.txt -col=2 -trimspaces "library"
csvfind -i text.txt -col=1 -trimspaces "red"

Doesn't work:
csvfind -i text.txt -col=2 -trimspaces "field"
csvfind -i text.txt -col=1 -trimspaces "yellow"

**Comment by rsdoiel** [comment]
This is fixed in the v0.0.23-pre
