### ISSUE TITLE
installation via homebrew

### ISSUE THREAD

**Issue by c33s** [caltechlibrary/datatools#4]
would be nice if it would be installable via homebrew

https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://docs.brew.sh/Formula-Cookbook

**Comment by rsdoiel** [comment]
Hello c33s,

Thank you for taking the time to submit an issue. I am very sorry to take five months to respond.  It's been a crazy year.

I've given this a little thought and I apologize for not taking your up on Homebrew packaging suggestion.  At Caltech Library we haven't standardized around one package system for our macOS community.  If I support one package system I need to support all of them. At last count that would be homebrew, MacPorts, Miniconda for macOS. There are several more for Windows including Linux as a sub system variants. We have a mix distributions favored in our Linux community.

In practice this hasn't proven to be a problem with our Go based projects. On POSIX systems it's four commands (two if they use a web browser). I commonly send instructions like this via email. Here's an example of instructions I would send someone with a fancy M1 Mac.

```bash
cd $HOME/Downloads
curl -O https://github.com/caltechlibrary/datatools/releases/download/v1.0.2/datatools-v1.0.2-macos-arm64.zip
unzip datatools-v1.0.2-macos-arm64.zip
cp bin/* $HOME/bin
```

This presumes we've standardize on including `$HOME/bin` in the default PATH which we did some time ago. This was made easy for us by our Library's IT staff who manage staff and patron machines.

That said, datatools like many Caltech Library projects is open source.  You or someone else can package the releases yourself as long as you respect the LICENSE terms.

All the best,

Robert Doiel
